periodic = true

[machines.m1]

[machines.m2]
speed = 1
setup_time = 1
teardown_time = 1

[jobs.j1]
period = 20
completion_time = 5
processing_times.m1 = 5

[jobs.j2]
period = 40
machine = "m2"
processing_times = 3
deadline = 15
completion_time_weight = 1

[jobs.j3]
period = 40
processing_times.m1 = 1
processing_times.m2 = 3
release_time = 10
deadline = 20
predecessors.j2.completion_time_wrt_weight = 2

[jobs.j4]
period = 20
processing_times.m1 = 1
same_machine_jobs = ["j3"]
completion_time_weight = -1
[jobs.j4.predecessors]
j1 = { time_lag = 5, slack_time = 10 }
j2.time_lag = 0

[jobs.j5]
period = 30
processing_times = 2
different_machine_jobs = ["j1"]

[jobs.j6]
period = 120
start_time = 119
processing_times = 2

# periodic = true/false
# [machines.machine_name]
# speed
# setup_time
# teardown_time
# [jobs.job_name]
# period
# start_time
# completion_time
# machine
# same_machine_jobs
# different_machine_jobs
# processing_times
# release_time
# deadline
# completion_time_weight
# flow_time_weight
# earliness_weight
# [jobs.job_name.predecessors.predecessor_job_name]
# start_time_wrt
# completion_time_wrt
# time_lag
# slack_time
# completion_time_wrt_weight
# flow_time_wrt_weight
# earliness_wrt_weight
